datacommons/urls.py
from django.conf.urls import patterns, include, url
from .csvs import views as csv
from .docs import views as doc
from .schemas import views as schemas
from .api import views as api
from .shapefiles import views as shapefile
from .accounts import views as accounts
from .querybuilder import views as querybuilder

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', accounts.login, name='home'),

    # csvs
    url(r'^csv/upload/?$', csv.upload, name='csv-upload'),
    url(r'^csv/preview/?$', csv.preview, name="csv-preview"),

    # shapefiles
    url(r'^shapefile/upload/?$', shapefile.upload, name='shapefile-upload'),
    url(r'^shapefile/preview/?$', shapefile.preview, name="shapefile-preview"),

    # documents
    url(r'^doc/upload/?$', doc.upload, name='doc-upload'),
    url(r'^doc/?$', doc.all, name='doc-all'),
    url(r'^doc/download/(\d+)?$', doc.download, name='doc-download'),

    # query builder
    url(r'^querybuilder/?$', querybuilder.build, name="querybuilder-build"),
    url(r'^querybuilder/preview/?$', querybuilder.preview, name="querybuilder-preview"),
    url(r'^querybuilder/preview/(?P<sql>.*)/?$', querybuilder.preview, name="querybuilder-preview"),

    # schemas
    url(r'^schemas/tables/?$', schemas.tables, name="schemas-tables"),
    url(r'^schemas/show/(.*)/(.*)/?$', schemas.show, name="schemas-show"),
    url(r'^schema/permissions/?$', schemas.permissions, name="schemas-permissions"),
    url(r'^schema/users/?$', schemas.users, name="schemas-users"),
    url(r'^schema/grant/?$', schemas.grant, name="schemas-grant"),
    url(r'^schema/permissions/(\d+)/?$', schemas.permissionsDetail, name="schemas-permissions-detail"),
    url(r'^schemas/create/?$', schemas.create, name="schemas-create"),
    url(r'^schemas/restore/(\d+)/?$', schemas.restore, name="schemas-restore"),
    url(r'^schemas/delete/(.*)/(.*)/?$', schemas.delete, name="schemas-delete"),

    # api
    url(r'^api/schemas/(.*)/tables/(.*)\.(.*)$', api.view, name="api-schemas-tables"),


    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # registration
    url(r'^register/?$', accounts.register, name="register"),
    url(r'^accounts/login/?$', accounts.login, name="login"),
    url(r'^accounts/profile/?$', accounts.profile, name="profile"),
    url(r'^accounts/logout/?$', 'django.contrib.auth.views.logout', {"next_page": "/"}, name="logout"),
    url(r'^accounts/settings/?$', accounts.settings, name="settings"),
    url(r'^accounts/password/?$', accounts.password, name="password"),

    # reset password
    url(r'^accounts/reset/?$', 'django.contrib.auth.views.password_reset', {"from_email": "django@pdx.edu"}, name="password_reset"),
    url(r'^accounts/reset/done/?$', 'django.contrib.auth.views.password_reset_done', name="password_reset_done"),
    url(r'^accounts/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)$', 'django.contrib.auth.views.password_reset_confirm', name="password_reset_confirm"),
    url(r'^accounts/reset/complete/?$', 'django.contrib.auth.views.password_reset_complete', name="password_reset_complete"),
)

datacommons/api/models.py
from django.db import models

class DownloadLog(models.Model):
    download_id = models.AutoField(primary_key=True)
    file_extension = models.CharField(max_length=4)
    downloaded_on = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey("accounts.User", null=True)
    table = models.ForeignKey("schemas.TableOrView")
    version = models.ForeignKey("schemas.Version", null=True)

    class Meta:
        db_table = 'downloadlog'

datacommons/csvs/models.py
from django.db import models
from datacommons.importable.models import ImportableUpload
from datacommons.unicodecsv import UnicodeReader
from datacommons.utils.dbhelpers import sanitize, inferColumnTypes

# Create your models here.
class CSVImport(ImportableUpload):
    ALLOWED_CONTENT_TYPES = [
        'text/csv', 
        'application/vnd.ms-excel', 
        'text/comma-separated-values',
    ]

    class Meta:
        proxy = True

    def parse(self):
        """Parse a CSV and return the header row, some of the data rows and
        inferred data types"""
        rows = []
        max_rows = 10
        # read in the first few rows, and save to a buffer.
        # Continue reading to check for any encoding errors
        i = -1
        try:
            last_row = None
            for i, row in enumerate(self):
                if i < max_rows:
                    rows.append(row)
                if last_row != None and len(last_row) != len(row):
                    raise ValueError("CSV rows are not all the same length. Or maybe you have an extra newline at the bottom of your file")
                last_row = row
        except UnicodeDecodeError as e:
            # tack on the line number to the exception so the caller can know
            # which line the error was on. The +2 is because i starts at 0, *and*
            # i in not incremented when the exception is thrown
            e.line = (i + 2)
            raise

        header = [sanitize(c) for c in self.header()]
        data = rows
        types = inferColumnTypes(data)
        return header, data, types

    def header(self):
        with open(self.path, 'r') as csvfile:
            reader = UnicodeReader(csvfile)
            for i, row in enumerate(reader):
                return [col.strip() for col in row]

    def __iter__(self):
        with open(self.path, 'r') as csvfile:
            reader = UnicodeReader(csvfile)
            for i, row in enumerate(reader):
                # skip over the header row
                if i == 0: continue
                yield [col.strip() for col in row]

datacommons/schemas/models.py
import itertools
from django.utils.datastructures import SortedDict
from django.conf import settings as SETTINGS
from django.db import models, connection, transaction, DatabaseError, connections

AUDIT_SCHEMA_NAME = "_version"

class SchemataItem(object):
    """A base class for all items that represent schemata (Schemas, Tables, Columns)"""
    def __unicode__(self):
        return self.name

class Schema(SchemataItem):
    """
    This isn't really a model, it represents a Schema in the database. And allows a schema to be created
    """
    def __init__(self, name):
        self.tables = []
        self.views = []
        self.name = name

    def __iter__(self):
        return iter(self.tables + self.views)

    @classmethod
    def create(cls, name):
        name = sanitize(name)
        cursor = connection.cursor()
        # we aren't using the second parameter to execute() to pass the name in
        # because we already (hopefully) escaped the input
        cursor.execute("CREATE SCHEMA %s" % name)

        # use the stored proc created by mharvey to setup the proper perms on the
        # table
        cursor.execute("SELECT dc_set_perms(%s);", (name,))


class TableOrView(models.Model):
    """The Table model and View models are both proxies for this."""
    table_id = models.AutoField(primary_key=True)
    # the name of the view/table itself
    name = models.CharField(max_length=255)
    # the name of the schema this table belongs in
    schema = models.CharField(max_length=255)
    created_on = models.DateTimeField(null=True, default=None)
    # whether this object represents a table or a view
    is_view = models.BooleanField(default=False, blank=True)

    owner = models.ForeignKey('accounts.User', related_name="+")
    
    class Meta:
        db_table = 'table'
        ordering = ['schema', 'name']

    def __unicode__(self):
        return u'%s' % (self.name)


class View(SchemataItem, TableOrView):
    """This model represents a view in a schema"""
    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        super(View, self).__init__(*args, **kwargs)
        self.columns = []
        self.name = self.name or kwargs.pop("name", None)
        self.is_view = True

    def toJSON(self):
        return {"name": self.name, "columns": self.columns, "is_view": self.is_view}

    def create(self, sql):
        # this will raise a database Error is there is a problem with the SQL (hopefully)
        SQLHandle(sql).count()
        cursor = connection.cursor()
        cursor.execute("SELECT dc_create_view(%s, %s, %s)", (self.schema, self.name, sql))

    def delete(self):
        cursor = connection.cursor()
        cursor.execute('SELECT dc_drop_view(%s,%s)', (sanitize(self.schema), sanitize(self.name)))
        super(View, self).delete()


class TableManager(models.Manager):
    def get_queryset(self):
        return super(TableManager, self).get_queryset().filter(is_view=False)

    def groupedBySchema(self, owner=None, include_views=False):
        # build a set of all the (schema, table) tuples in the db
        topology = getDatabaseTopology()
        s = set()
        for schema in topology:
            for table in schema.tables:
                s.add((schema.name, table.name))

        if owner is None:
            tables = Table.objects.exclude(created_on=None)
        else:
            tables = Table.objects.filter(owner=owner).exclude(created_on=None)

        if not include_views:
            tables = tables.exclude(is_view=True)

        results = SortedDict()
        for table in tables:
            # the tables in the database, and the tables in the "table" table
            # might not quite match. So only return the results where there is a match
            if (table.schema, table.name) in s:
                results.setdefault(table.schema, []).append(table)

        return results


class Table(SchemataItem, TableOrView):
    """
    This object represents a table in a schema
    """
    objects = TableManager()

    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        super(Table, self).__init__(*args, **kwargs)
        self.columns = []
        self.name = self.name or kwargs.pop("name", None)
        self.is_view = False

    def __iter__(self):
        return iter(self.columns)

    def toJSON(self):
        return {"name": self.name, "columns": self.columns, "is_view": self.is_view}

    def auditTableName(self):
        return "_" + self.schema + "_" + self.name

    def canDo(self, user, permission_bit, perm=None):
        # owner can always do stuff
        if self.owner == user:
            return True

        try:
            if not perm:
                perm = TablePermission.objects.get(table=self, user=user)
        except TablePermission.DoesNotExist:
            return False

        return bool(perm.permission & permission_bit)

    def canInsert(self, user, perm=None):
        return self.canDo(user, TablePermission.INSERT, perm)
    def canUpdate(self, user, perm=None):
        return self.canDo(user, TablePermission.UPDATE, perm)
    def canDelete(self, user, perm=None):
        return self.canDo(user, TablePermission.DELETE, perm)
    def canRestore(self, user, perm=None):
        return self.canInsert(user, perm) and self.canUpdate(user, perm) and self.canDelete(user, perm)

    def grant(self, user, perm_bit):
        try:
            perm = TablePermission.objects.get(table=self, user=user)
        except TablePermission.DoesNotExist:
            perm = TablePermission(table=self, user=user, permission=0)

        perm.permission |= perm_bit
        perm.save()

    def revoke(self, user, perm_bit):
        try:
            perm = TablePermission.objects.get(table=self, user=user)
        except TablePermission.DoesNotExist:
            perm = TablePermission(table=self, user=user, permission=0)

        perm.permission &= ~perm_bit
        perm.save()

        # if there are no permissions set, just delete the record
        if perm.permission == 0:
            perm.delete()

    def permissionGrid(self):
        perms = TablePermission.objects.filter(table=self).select_related("user")
        rows = {}
        for perm in perms:
            item = rows.setdefault(perm.user, {})
            item['can_insert'] = self.canInsert(perm.user, perm)
            item['can_update'] = self.canUpdate(perm.user, perm)
            item['can_delete'] = self.canDelete(perm.user, perm)

        return rows

    def create(self, columns):
        column_names = [col.name for col in columns if col.type != ColumnTypes.GEOMETRY]
        column_types = [col.type for col in columns if col.type != ColumnTypes.GEOMETRY]

        # santize all the names
        schema_name = sanitize(self.schema)
        table_name = sanitize(self.name)

        # sanitize 
        names = []
        for name in column_names:
            names.append(sanitize(name))
        column_names = names

        names = []
        for name in [col.name for col in columns if col.is_pk]:
            names.append(sanitize(name))
        primary_keys = names

        # get all the column type names
        types = []
        for type in column_types:
            types.append(ColumnTypes.toPGType(int(type)))

        column_sql = []
        for i in range(len(column_names)):
            column_sql.append(column_names[i] + " " + types[i])
        column_sql = ",".join(column_sql)

        # sure hope this is SQL injection proof
        create_table_sql = """
            CREATE TABLE "%s"."%s" (
                %s
            );
        """ % (schema_name, table_name, column_sql)
        cursor = connection.cursor()
        cursor.execute(create_table_sql)

        # now add the audit table
        audit_table_name = self.auditTableName()
        audit_table_sql = """
            CREATE TABLE "%s"."%s" (
                _version_id INTEGER NOT NULL REFERENCES "version" ("version_id") DEFERRABLE INITIALLY DEFERRED,
                _inserted_or_deleted smallint,
                %s
            );
        """ % (AUDIT_SCHEMA_NAME, audit_table_name, column_sql)
        cursor.execute(audit_table_sql)

        # add the primary key, if there is one
        if len(primary_keys):
            sql = """ALTER TABLE "%s"."%s" ADD PRIMARY KEY (%s);""" % (schema_name, table_name, ",".join(primary_keys))
            cursor.execute(sql)

            audit_pks = primary_keys + ['_version_id', '_inserted_or_deleted']
            sql = """ALTER TABLE "%s"."%s" ADD PRIMARY KEY (%s);""" % (AUDIT_SCHEMA_NAME, audit_table_name, ",".join(audit_pks))
            cursor.execute(sql)

        has_geom = any(col.srid for col in columns)
        if has_geom:
            # find the column with the geometry
            col = [col for col in columns if col.srid][0]
            self._addGeometryColumn(schema_name, table_name, col)
            self._addGeometryColumn(AUDIT_SCHEMA_NAME, audit_table_name, col)

        # run morgan's fancy proc
        cursor.execute("SELECT dc_set_perms(%s, %s);", (schema_name, table_name))
        cursor.execute("SELECT dc_set_perms(%s, %s);", (AUDIT_SCHEMA_NAME, audit_table_name))

    def _addGeometryColumn(self, schema_name, table_name, col):
        cursor = connection.cursor()
        cursor.execute("""SELECT AddGeometryColumn(%s, %s, %s, %s, %s, 2)""",
            (schema_name, table_name, col.name, SETTINGS.OFFICIAL_SRID, col.geom_type))


class TablePermission(models.Model):
    # permissions need to be powers of 2 so we can do bitwise ANDs and ORs
    INSERT = 1
    UPDATE = 2
    DELETE = 4

    table_permission_id = models.AutoField(primary_key=True)
    table = models.ForeignKey('Table')
    user = models.ForeignKey('accounts.User')
    permission = models.IntegerField()

    class Meta:
        db_table = 'tablepermission'
        unique_together = ("table", "user")


class ColumnTypes:
    """An enum for column types"""
    INTEGER = 1

datacommons/csvs/forms.py
from .models import CSVImport
from datacommons.importable.forms import ImportableUploadForm, ImportablePreviewForm

class CSVUploadForm(ImportableUploadForm):
    MODEL = CSVImport 

class CSVPreviewForm(ImportablePreviewForm):
    MODEL = CSVImport 

datacommons/csvs/views.py
from django.contrib.auth.decorators import login_required
from .forms import CSVUploadForm, CSVPreviewForm
from datacommons.importable.views import upload as upload_view, preview as preview_view

@login_required
def upload(request):
    """Display the CSV upload form"""
    return upload_view(request, CSVUploadForm, 'csv/upload.html', 'csv-preview', filetype="CSV")

@login_required
def preview(request):
    """Finalize the CSV upload"""
    return preview_view(request, CSVPreviewForm, 'csv/preview.html')

datacommons/templates/csv/preview.html
{% extends "main.html" %}
{% block content %}
{% load dictlookup %}

<div class="alert alert-info"><strong>Note:</strong> Table and column names must be lower case, start with a letter, and
consist only of the characters <samp>a-z</samp>, <samp>0-9</samp> and <samp>_</samp>. They can contain, at most, 63 characters.</div>

<form action="" method="post" class="strong-labels">
    {% csrf_token %}
    {% if form.errors or error %}
        <div class="alert alert-error">
            <strong>Some errors were detected!</strong> You must fix them before you can continue.
        </div>
    {% endif %}

    {% if error %}
        <div class="alert alert-error">
            {{ error }}
        </div>
    {% endif %}

    {{ form.non_field_errors }}

    {% if upload.mode == upload.CREATE %}
        <label>Give this table a name:</label>
        {{ form.table.errors }}
        {{ form.table }}
    {% elif upload.mode == upload.APPEND %}
        <h2>Append to {{ upload.table }}</h2>
    {% elif upload.mode == upload.DELETE %}
        <h2>Delete rows from {{ upload.table }}</h2>
    {% elif upload.mode == upload.UPSERT %}
        <h2>Insert/Update rows in {{ upload.table }}</h2>
    {% elif upload.mode == upload.REPLACE %}
        <h2>Replace all rows in {{ upload.table }}</h2>
    {% endif %}

    {% if form.srid %}
        <label>SRID (projection)</label>
        {{ form.srid }}
    {% endif %}

    <div id="preview-wrapper">
        <table id="preview">
            <thead>
                <tr class="preview">
                    {% if upload.mode == upload.CREATE %}
                        <th colspan="{{ form.nameFields|length }}">Give each column a name:</th>
                    {% else %}
                        <th colspan="{{ form.nameFields|length }}">For each column, select which field in the table corresponds to the data in the column.</th>
                    {% endif %}
                </tr>
                <tr class="preview">
                    {% if upload.mode == upload.CREATE %}
                        {% for field in form.nameFields %}
                            <td>
                                {{ field.errors }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    {% else %}
                        {% for field in form.nameFields %}
                            <td class="select-type">
                                {{ field.errors }} 
                                {{ field }}
                            </td>
                        {% endfor %}
                    {% endif %}
                </tr>
                <tr class="preview">
                    {% if upload.mode == upload.CREATE %}
                        <th colspan="{{ form.nameFields|length }}">Choose a datatype for each column:</th>
                    {% endif %}
                </tr>
                <tr class="preview">
                    {% if upload.mode == upload.CREATE %}
                        {% for field in form.typeFields %}
                            <td>
                                {{ field }}
                            </td>
                        {% endfor %}
                    {% else %}
                        {% for field in form.nameFields %}
                            <td class="field-type" id="typelabel-{{ forloop.counter0}}"></td>
                        {% endfor %}
                    {% endif %}
                </tr>
                {% if upload.mode == upload.CREATE %}
                    <tr>
                        <th colspan="{{ form.nameFields|length }}">Check the checkbox if this field is the primary, or part of it  <i class="icon-info-sign" title="Some combination of rows must uniquely identify the row."></i></th>
                    </tr>
                    <tr class="light-labels">
                        {% for field in form.pkFields %}
                            <td><label class="checkbox">{{ field }}Primary Key</label></td>
                        {% endfor %}
                    </tr>
                {% endif %}
                <tr>
                    <th colspan="{{ form.nameFields|length }}">Data Preview</th>
                </tr>
            </thead>
            <tbody>
                {% block data_loop %}
                    {% for row in data %}
                        <tr>
                            {% for col in row %}
                                <td>{{ col }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                {% endblock %}
            </tbody>
        </table>
    </div>

    <br />
    <input type="hidden" name="upload_id" value="{{ upload.pk }}" />
    <input type="submit" name="submit" value="Import" id="submit" />
</form>

<script type="text/javascript">
{% if upload.mode == upload.APPEND %}
    var COL_NAME_TO_HUMAN_TYPE = {{ col_name_to_human_type_json|safe }};

    $(document).ready(function(){
        // when a column name is selected from the column drop down, change the type
        // text below it to match the type of the column selected
        $('.select-type select').bind('click blur change', function(e){
            var el = $(this);
            var id = el.attr('id').split("-")[1]
            var name = el.val();
            var label = COL_NAME_TO_HUMAN_TYPE[name];
            $('#typelabel-' + id).text(label);
        });

        $('.select-type select').click()
    });
{% endif %}

</script>

{% endblock %}

datacommons/templates/csv/review.html
{% extends "base.html" %}
{% block body %}
{{ cols|pprint }}
<h1>{{ upload.schema }}.{{ upload.table }}</h1>
<table>
    <thead>
        <tr>
        {% for col in cols %}
            <th>{{ col.name }}</th>
        {% endfor %}
        </tr>
    </thead>
    {% for row in rows %}
        <tr>
            {% for col in row %}
                <td>{{ col }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
{% endblock %}

datacommons/templates/csv/upload.html
{% extends "main.html" %}
{% block content %}
<h2>Import a {{ filetype }}</h2>

<form action="" method="post" enctype="multipart/form-data" class="strong-labels">
    {% csrf_token %}
    {% if form.errors %}
        <div class="alert alert-error">
            <strong>Some errors were detected!</strong> You must fix them before you can continue.
        </div>
    {% endif %}

    <label>Which schema should this {{ filetype }} be imported into?</label>
    {{ form.schemas.errors }}

    {{ form.schema }}

    <label>Do you want to:</label>
    {{ form.mode.errors }}
    <div class="radio light-labels smashed-labels">
        {% for choice in form.mode %}
            <label>{{ choice.tag }} {{ choice.choice_label }}</label>
        {% endfor %}
    </div>

    <div id="select-table" style="display:none">
        <label>Which table do you want to update?</label>
        {{ form.table.errors }}
        {{ form.table }}

        <div id="table-description">
            <p><strong>Table fields:</strong></p>
            <ol id="column-list"></ol>
        </div>
    </div>

    <label>Upload a {{ filetype }}</label>
    {{ form.file.errors }}
    {% if filetype == "CSV" %}
        <p>The first row of the CSV is assumed to be the column headings.</p>
    {% endif %}
    {{ form.file }}

    <br />
    <br />
    <input type="submit" name="submit" value="Continue" id="submit" />
</form>

<script type="text/javascript">
var SCHEMAS = {{ schemas_json|safe }};
function getSchemaByName(name){
    for(var i = 0; i < SCHEMAS.length; i++){
        if(SCHEMAS[i].name == name) return SCHEMAS[i];
    }
    return null;
}

function getTableByName(schema, name){
    for(var i = 0; i < schema.tables.length; i++){
        if(schema.tables[i].name == name) return schema.tables[i];
    }
}

$(document).ready(function(){
    // when the schema select box changes, we need to update all the tables in
    // the table select box
    $('#id_schema').on('change', function(){
        populateTables();
    });

    // when a mode is selected, we need to decide to display the table drop
    // down box
    $('input[name="mode"]').bind('click change', function(){
        var val = $('input[name="mode"]:checked').val()
        if(val == "{{ ImportableUpload.CREATE }}"){
            // creating a table doesn't require selecting one, so hide the
            // table list
            $('#select-table').hide();
        } else if(
            val == "{{ ImportableUpload.APPEND }}" || 
            val == "{{ ImportableUpload.UPSERT }}" ||
            val == "{{ ImportableUpload.REPLACE }}" ||
            val == "{{ ImportableUpload.DELETE }}") {
            // appending or upserting requires the user to select a table
            // so show the select box, update the list, and show the column
            // info div
            $('#select-table').show();
            populateTables();
        }
    })
    
    // when a table is selected from the drop down, we need to update the
    // column info div
    $('#id_table').on('click change', function(){
        populateTables();
    });

    // when the page loads, fire off this event which handles all the logic for
    // hiding/displaying the table stuff
    $('input[name="mode"]').change();
});

function populateTables(){
    // get the schema name
    var schema = $('#id_schema').val();
    // get all the tables out of the schema meta data
    var s = getSchemaByName(schema);
    if(s){
        var tables = s.tables;
    } else {
        var tables = []
    }
    // get the currently selected table, so we can restore the selected value,
    // when the option list is regenerated
    var original_selection = $('#id_table').val();

    var t = $('#id_table');
    // reset the table options
    t.html("")
    // hide the table description
    $('#table-description').hide();
    if(schema == ""){ 
        return;
    }

    // add a blank option
    t.append("<option value=''></option>")
    // for each table, add an option in the drop down list for it
    for(var i = 0; i < tables.length; i++){
        if(tables[i].is_view) continue;
        var name = tables[i].name
        var el = t.append("<option value='" + name + "'>" + name + "</option>");
    }

    // restore the selected option (since we just wiped out the whole select
    // box, and erased their selection)
    $('#id_table option').each(function(){
        if($(this).text() == original_selection){
            $(this).attr('selected', true);
        }
    });

    var table = $("#id_table option:selected").val();
    showColumns(schema, table);
}

function showColumns(schema, table){
    if(!schema || !table){
        return;
    }
    // get the list of cols out of the schema meta data
    try {
        var schema = getSchemaByName(schema)
        var cols = getTableByName(schema, table).columns
    } catch(e){
        return;
    }

    var info = []
    for(var i = 0; i < cols.length; i++){
        col = cols[i];
        info.push("<li>") 
        if(col.is_pk) info.push("<strong>")
        info.push(col.name)
        if(col.is_pk) info.push("</strong>")
        
        info.push(" (<em>")
        info.push(col.type_label.toLowerCase())
        info.push("</em>)</li>");
    }
    $('#column-list').html(info.join(""))
    $('#table-description').show();
}

</script>
{% endblock %}