datacommons/urls.py
from django.conf.urls import patterns, include, url
from .csvs import views as csv
from .docs import views as doc
from .schemas import views as schemas
from .api import views as api
from .shapefiles import views as shapefile
from .accounts import views as accounts
from .querybuilder import views as querybuilder

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', accounts.login, name='home'),

    # csvs
    url(r'^csv/upload/?$', csv.upload, name='csv-upload'),
    url(r'^csv/preview/?$', csv.preview, name="csv-preview"),

    # shapefiles
    url(r'^shapefile/upload/?$', shapefile.upload, name='shapefile-upload'),
    url(r'^shapefile/preview/?$', shapefile.preview, name="shapefile-preview"),

    # documents
    url(r'^doc/upload/?$', doc.upload, name='doc-upload'),
    url(r'^doc/?$', doc.all, name='doc-all'),
    url(r'^doc/download/(\d+)?$', doc.download, name='doc-download'),

    # query builder
    url(r'^querybuilder/?$', querybuilder.build, name="querybuilder-build"),
    url(r'^querybuilder/preview/?$', querybuilder.preview, name="querybuilder-preview"),
    url(r'^querybuilder/preview/(?P<sql>.*)/?$', querybuilder.preview, name="querybuilder-preview"),

    # schemas
    url(r'^schemas/tables/?$', schemas.tables, name="schemas-tables"),
    url(r'^schemas/show/(.*)/(.*)/?$', schemas.show, name="schemas-show"),
    url(r'^schema/permissions/?$', schemas.permissions, name="schemas-permissions"),
    url(r'^schema/users/?$', schemas.users, name="schemas-users"),
    url(r'^schema/grant/?$', schemas.grant, name="schemas-grant"),
    url(r'^schema/permissions/(\d+)/?$', schemas.permissionsDetail, name="schemas-permissions-detail"),
    url(r'^schemas/create/?$', schemas.create, name="schemas-create"),
    url(r'^schemas/restore/(\d+)/?$', schemas.restore, name="schemas-restore"),
    url(r'^schemas/delete/(.*)/(.*)/?$', schemas.delete, name="schemas-delete"),

    # api
    url(r'^api/schemas/(.*)/tables/(.*)\.(.*)$', api.view, name="api-schemas-tables"),


    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # registration
    url(r'^register/?$', accounts.register, name="register"),
    url(r'^accounts/login/?$', accounts.login, name="login"),
    url(r'^accounts/profile/?$', accounts.profile, name="profile"),
    url(r'^accounts/logout/?$', 'django.contrib.auth.views.logout', {"next_page": "/"}, name="logout"),
    url(r'^accounts/settings/?$', accounts.settings, name="settings"),
    url(r'^accounts/password/?$', accounts.password, name="password"),

    # reset password
    url(r'^accounts/reset/?$', 'django.contrib.auth.views.password_reset', {"from_email": "django@pdx.edu"}, name="password_reset"),
    url(r'^accounts/reset/done/?$', 'django.contrib.auth.views.password_reset_done', name="password_reset_done"),
    url(r'^accounts/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)$', 'django.contrib.auth.views.password_reset_confirm', name="password_reset_confirm"),
    url(r'^accounts/reset/complete/?$', 'django.contrib.auth.views.password_reset_complete', name="password_reset_complete"),
)

datacommons/schemas/models.py
import itertools
from django.utils.datastructures import SortedDict
from django.conf import settings as SETTINGS
from django.db import models, connection, transaction, DatabaseError, connections

AUDIT_SCHEMA_NAME = "_version"

class SchemataItem(object):
    """A base class for all items that represent schemata (Schemas, Tables, Columns)"""
    def __unicode__(self):
        return self.name

class Schema(SchemataItem):
    """
    This isn't really a model, it represents a Schema in the database. And allows a schema to be created
    """
    def __init__(self, name):
        self.tables = []
        self.views = []
        self.name = name

    def __iter__(self):
        return iter(self.tables + self.views)

    @classmethod
    def create(cls, name):
        name = sanitize(name)
        cursor = connection.cursor()
        # we aren't using the second parameter to execute() to pass the name in
        # because we already (hopefully) escaped the input
        cursor.execute("CREATE SCHEMA %s" % name)

        # use the stored proc created by mharvey to setup the proper perms on the
        # table
        cursor.execute("SELECT dc_set_perms(%s);", (name,))


class TableOrView(models.Model):
    """The Table model and View models are both proxies for this."""
    table_id = models.AutoField(primary_key=True)
    # the name of the view/table itself
    name = models.CharField(max_length=255)
    # the name of the schema this table belongs in
    schema = models.CharField(max_length=255)
    created_on = models.DateTimeField(null=True, default=None)
    # whether this object represents a table or a view
    is_view = models.BooleanField(default=False, blank=True)

    owner = models.ForeignKey('accounts.User', related_name="+")
    
    class Meta:
        db_table = 'table'
        ordering = ['schema', 'name']

    def __unicode__(self):
        return u'%s' % (self.name)


class View(SchemataItem, TableOrView):
    """This model represents a view in a schema"""
    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        super(View, self).__init__(*args, **kwargs)
        self.columns = []
        self.name = self.name or kwargs.pop("name", None)
        self.is_view = True

    def toJSON(self):
        return {"name": self.name, "columns": self.columns, "is_view": self.is_view}

    def create(self, sql):
        # this will raise a database Error is there is a problem with the SQL (hopefully)
        SQLHandle(sql).count()
        cursor = connection.cursor()
        cursor.execute("SELECT dc_create_view(%s, %s, %s)", (self.schema, self.name, sql))

    def delete(self):
        cursor = connection.cursor()
        cursor.execute('SELECT dc_drop_view(%s,%s)', (sanitize(self.schema), sanitize(self.name)))
        super(View, self).delete()


class TableManager(models.Manager):
    def get_queryset(self):
        return super(TableManager, self).get_queryset().filter(is_view=False)

    def groupedBySchema(self, owner=None, include_views=False):
        # build a set of all the (schema, table) tuples in the db
        topology = getDatabaseTopology()
        s = set()
        for schema in topology:
            for table in schema.tables:
                s.add((schema.name, table.name))

        if owner is None:
            tables = Table.objects.exclude(created_on=None)
        else:
            tables = Table.objects.filter(owner=owner).exclude(created_on=None)

        if not include_views:
            tables = tables.exclude(is_view=True)

        results = SortedDict()
        for table in tables:
            # the tables in the database, and the tables in the "table" table
            # might not quite match. So only return the results where there is a match
            if (table.schema, table.name) in s:
                results.setdefault(table.schema, []).append(table)

        return results


class Table(SchemataItem, TableOrView):
    """
    This object represents a table in a schema
    """
    objects = TableManager()

    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        super(Table, self).__init__(*args, **kwargs)
        self.columns = []
        self.name = self.name or kwargs.pop("name", None)
        self.is_view = False

    def __iter__(self):
        return iter(self.columns)

    def toJSON(self):
        return {"name": self.name, "columns": self.columns, "is_view": self.is_view}

    def auditTableName(self):
        return "_" + self.schema + "_" + self.name

    def canDo(self, user, permission_bit, perm=None):
        # owner can always do stuff
        if self.owner == user:
            return True

        try:
            if not perm:
                perm = TablePermission.objects.get(table=self, user=user)
        except TablePermission.DoesNotExist:
            return False

        return bool(perm.permission & permission_bit)

    def canInsert(self, user, perm=None):
        return self.canDo(user, TablePermission.INSERT, perm)
    def canUpdate(self, user, perm=None):
        return self.canDo(user, TablePermission.UPDATE, perm)
    def canDelete(self, user, perm=None):
        return self.canDo(user, TablePermission.DELETE, perm)
    def canRestore(self, user, perm=None):
        return self.canInsert(user, perm) and self.canUpdate(user, perm) and self.canDelete(user, perm)

    def grant(self, user, perm_bit):
        try:
            perm = TablePermission.objects.get(table=self, user=user)
        except TablePermission.DoesNotExist:
            perm = TablePermission(table=self, user=user, permission=0)

        perm.permission |= perm_bit
        perm.save()

    def revoke(self, user, perm_bit):
        try:
            perm = TablePermission.objects.get(table=self, user=user)
        except TablePermission.DoesNotExist:
            perm = TablePermission(table=self, user=user, permission=0)

        perm.permission &= ~perm_bit
        perm.save()

        # if there are no permissions set, just delete the record
        if perm.permission == 0:
            perm.delete()

    def permissionGrid(self):
        perms = TablePermission.objects.filter(table=self).select_related("user")
        rows = {}
        for perm in perms:
            item = rows.setdefault(perm.user, {})
            item['can_insert'] = self.canInsert(perm.user, perm)
            item['can_update'] = self.canUpdate(perm.user, perm)
            item['can_delete'] = self.canDelete(perm.user, perm)

        return rows

    def create(self, columns):
        column_names = [col.name for col in columns if col.type != ColumnTypes.GEOMETRY]
        column_types = [col.type for col in columns if col.type != ColumnTypes.GEOMETRY]

        # santize all the names
        schema_name = sanitize(self.schema)
        table_name = sanitize(self.name)

        # sanitize 
        names = []
        for name in column_names:
            names.append(sanitize(name))
        column_names = names

        names = []
        for name in [col.name for col in columns if col.is_pk]:
            names.append(sanitize(name))
        primary_keys = names

        # get all the column type names
        types = []
        for type in column_types:
            types.append(ColumnTypes.toPGType(int(type)))

        column_sql = []
        for i in range(len(column_names)):
            column_sql.append(column_names[i] + " " + types[i])
        column_sql = ",".join(column_sql)

        # sure hope this is SQL injection proof
        create_table_sql = """
            CREATE TABLE "%s"."%s" (
                %s
            );
        """ % (schema_name, table_name, column_sql)
        cursor = connection.cursor()
        cursor.execute(create_table_sql)

        # now add the audit table
        audit_table_name = self.auditTableName()
        audit_table_sql = """
            CREATE TABLE "%s"."%s" (
                _version_id INTEGER NOT NULL REFERENCES "version" ("version_id") DEFERRABLE INITIALLY DEFERRED,
                _inserted_or_deleted smallint,
                %s
            );
        """ % (AUDIT_SCHEMA_NAME, audit_table_name, column_sql)
        cursor.execute(audit_table_sql)

        # add the primary key, if there is one
        if len(primary_keys):
            sql = """ALTER TABLE "%s"."%s" ADD PRIMARY KEY (%s);""" % (schema_name, table_name, ",".join(primary_keys))
            cursor.execute(sql)

            audit_pks = primary_keys + ['_version_id', '_inserted_or_deleted']
            sql = """ALTER TABLE "%s"."%s" ADD PRIMARY KEY (%s);""" % (AUDIT_SCHEMA_NAME, audit_table_name, ",".join(audit_pks))
            cursor.execute(sql)

        has_geom = any(col.srid for col in columns)
        if has_geom:
            # find the column with the geometry
            col = [col for col in columns if col.srid][0]
            self._addGeometryColumn(schema_name, table_name, col)
            self._addGeometryColumn(AUDIT_SCHEMA_NAME, audit_table_name, col)

        # run morgan's fancy proc
        cursor.execute("SELECT dc_set_perms(%s, %s);", (schema_name, table_name))
        cursor.execute("SELECT dc_set_perms(%s, %s);", (AUDIT_SCHEMA_NAME, audit_table_name))

    def _addGeometryColumn(self, schema_name, table_name, col):
        cursor = connection.cursor()
        cursor.execute("""SELECT AddGeometryColumn(%s, %s, %s, %s, %s, 2)""",
            (schema_name, table_name, col.name, SETTINGS.OFFICIAL_SRID, col.geom_type))


class TablePermission(models.Model):
    # permissions need to be powers of 2 so we can do bitwise ANDs and ORs
    INSERT = 1
    UPDATE = 2
    DELETE = 4

    table_permission_id = models.AutoField(primary_key=True)
    table = models.ForeignKey('Table')
    user = models.ForeignKey('accounts.User')
    permission = models.IntegerField()

    class Meta:
        db_table = 'tablepermission'
        unique_together = ("table", "user")


class ColumnTypes:
    """An enum for column types"""
    INTEGER = 1

datacommons/templates/schemas/create.html
{% extends "main.html" %}
{% block content %}
<h2>Create Schema</h2>
<form method="post" action="">
{% csrf_token %}
{{ form }}
<br />
<input type="submit" name="submit" value="Create" />
</form>
{% endblock %}

datacommons/templates/schemas/delete.html
{% extends "main.html" %}
{% block content %}
<h2>{{ table.schema }}.{{ table.name }}</h2>
<form method="post" action="">
    {{ form }}
    {% csrf_token %}
    <div class="alert alert-danger alert-block">
        <h4>Delete View</h4>
        <p>This operation cannot be reversed!</p>
    </div>
    <input type="submit" name="submit" value="Delete" class="btn btn-danger" />
    <a href="javascript:window.history.go(-1)" class="btn">Cancel</a>
</form>

{% endblock %}

datacommons/templates/schemas/list.html
{% extends "main.html" %}
{% block content %}
{% for schema in schemas %}
    <h3>{{ schema.name }}</h3>
    {% if schema.tables|length > 0 %}
        <h4>Tables</h4>
        <ol>
        {% for table in schema.tables %}
            <li>
                <a href="{% url "schemas-show" schema table %}">{{ table }}</a>
            </li>
        {% endfor %}
        </ol>
    {% endif %}

    {% if schema.views|length > 0 %}
        <h4>Views</h4>
        <ol>
        {% for table in schema.views %}
            <li>
                <a href="{% url "schemas-show" schema table %}">{{ table }}</a>
            </li>
        {% endfor %}
        </ol>
    {% endif %}

    {% if schema.views|length == 0 and schema.tables|length == 0 %}
        (empty)
    {% endif %}
{% endfor %}
{% endblock %}

datacommons/templates/schemas/permissions.html
{% extends "main.html" %}
{% block content %}
<script type="text/javascript">

$(document).ready(function(){
    bindAutoComplete();
    $('#form').submit(onSubmit);
});

function bindAutoComplete(){
    $('#id_user').autocomplete({
        source: function(request, response){
            $.getJSON("{% url 'schemas-users' %}", {term: request.term}, function(data){
                var options = []
                for(var i = 0; i < data.length; i++){
                    var user = data[i];
                    options.push({
                        label: user.first_name + " " + user.last_name + " (" + user.email + ")",
                        value: user.email,
                    });
                }
                response(options); 
            });
        }
    });
}

function onSubmit(e){
    e.preventDefault();
    $('#id_user').autocomplete("destroy");
    clearErrors();
    var form = $('#form').serialize();
    $.post("{% url 'schemas-grant' %}", form, function(data){
        var response = $.parseJSON(data);
        console.log(response);
        autocomplete_enabled = true;
        if(response.success){
            $('#id_user').val("")
            $('#id_user').select().focus()
            $('#success-message').show().fadeOut(1500)
        } else {
            showErrors(response.errors)
        }
        bindAutoComplete();
    })

    return false;
}

function clearErrors(){
    $('.permissions-errors').each(function(){ $(this).html(""); })
}

function showErrors(errors){
    for(var k in errors){
        var error_list = errors[k];
        var id = "#errors_" + k;
        var html = [];
        for(var i = 0; i < error_list.length; i++){
            html.push(error_list[i]);
        }
        $(id).append(html.join(","));
    }
}

</script>

<form action="" method="post" id="form" >
    {% csrf_token %}
    <h2>Grant/Revoke Permissions</h2>
    <div style="height:60px">
        <div class="alert alert-success" id="success-message" style="display:none">Permissions granted/revoked successfully!</div>
    </div>

    <table id="permissions-table">
        <tr>
            <td class="permission-cell no-margin">
                <div class="permissions-errors" id="errors_{{ form.option.html_name }}"></div>
                {{ form.option }}
            </td>
            <td class="permission-cell no-margin">
                <div class="permissions-errors" id="errors_{{ form.permissions.html_name }}"></div>
                {{ form.permissions }}
            </td>
            <td style="width:30px; text-align:center" class="permission-cell">
                on
            </td>
            <td rowspan="2" style="text-align:left" class="permission-cell">
                <div class="permissions-errors" id="errors_{{ form.tables.html_name }}"></div>
                {% for schema, field_list in form.schemas.items %}
                    <label><strong>{{ schema }}</strong></label>
                    {% for field in field_list %}
                        <label class="checkbox">{{ field }} {{ field.label }}
                            <a href="{% url 'schemas-permissions-detail' field.pk %}">(edit)</a>
                        </label>
                    {% endfor %}
                {% endfor %}
            </td>
            <td style="width:50px; text-align:center" class="permission-cell">
                to/from
            </td>
            <td class="permission-cell no-margin">
                <div class="permissions-errors" id="errors_{{ form.user.html_name }}"></div>
                {{ form.user }}
                <input type="submit" name="add" value="Apply" id="add" />
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</form>

{% endblock %}

datacommons/templates/schemas/permissions_detail.html
{% extends "main.html" %}
{% block content %}
<h2>{{ table.schema }}.{{ table.name }}</h2>
{% if form.fields|length != 0 %}
    <form method="post" action="">
        {% csrf_token %}
        <table class="table table-striped no-margin permissions-list-editor">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Insert</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for user, can_insert, can_update, can_delete in form.fieldIter %}
                    <tr>
                        <td>{{ user.email }}</td>
                        <th>{{ can_insert }}</th>
                        <th>{{ can_update }}</th>
                        <th>{{ can_delete }}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" name="submit" value="Save" />
    </form>
{% else %}
    <div class="alert alert-info">No permissions defined for this table</div>
{% endif %}

{% endblock %}

datacommons/templates/schemas/restore.html
{% extends "main.html" %}
{% block content %}
<h2>Restore {{ table.schema }}.{{ table.name }} to {{ version.created_on|date:"M-d-Y P" }}</h2>
<div class="alert alert-block alert-warning">
    Restoring a table will overwrite all data in the table, and replace it with the data from this version.
</div>

<form method="post" action="">
    {% csrf_token %}
    <button type="submit" name="submit" class="btn btn-warning">Restore</button>
    <a href="{% url 'schemas-show' table.schema table.name %}?version_id={{ version.pk }}" class="btn">Cancel</a>
</form>

{% endblock %}

datacommons/templates/schemas/show.html
{% extends "main.html" %}
{% block content %}

<div class="row">
    <div class="span8">
        <h2>{{ table.schema }}.{{ table.name }}</h2>
        <p><strong>Export:</strong> <a href="{% url "api-schemas-tables" table.schema table.name 'csv' %}?version_id={{ version.pk }}">CSV</a> | 
        <a href="{% url "api-schemas-tables" table.schema table.name 'json' %}?version_id={{ version.pk }}">JSON</a> 
        {% if has_geom %}| 
            <a href="{% url "api-schemas-tables" table.schema table.name 'kml' %}?version_id={{ version.pk }}">KML</a> |
            <a href="{% url "api-schemas-tables" table.schema table.name 'zip' %}?version_id={{ version.pk }}">Shapefile (zip)</a>
        {% endif %}</p>

        {% include '_paginator.html' with paginator=rows %}

        <div class="overflowed">
            <table class="table table-striped">
                <thead>
                    <tr>
                    {% for col in cols %}
                        <th>{{ col.name }}</th>
                    {% endfor %}
                    </tr>
                    <tr>
                    {% for col in cols %}
                        <th class="field-type">{{ col.type_label }}</th>
                    {% endfor %}
                    </tr>
                </thead>
                {% for row in rows %}
                    <tr>
                        {% for col in row %}
                            <td>
                                {% if col.geom_type %}
                                    {{ col|truncatewords:1 }}
                                {% else %}
                                    {{ col }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>

        {% include '_paginator.html' with paginator=rows %}
    </div>

    <div class="span4">
        {% if versions %}
            <h4>Versions</h4>
            <ol>
                {% for v in versions %}
                    <li><a {% if version.pk == v.pk %}style="font-weight:bold"{% endif %}href="?version_id={{ v.pk }}" title="{{ v.user }}">{{ v.created_on|date:"M-d-Y P" }}</a></li>
                {% endfor %}
            </ol>
        {% endif %}

        {% if show_restore_link %}
            <a href="{% url 'schemas-restore' version.pk %}" class="btn btn-small btn-warning">Restore to this version</a>
        {% endif %}

        {% if table.is_view and table.owner == user %}
            <a href="{% url 'schemas-delete' table.schema table.name %}" class="btn btn-danger">Delete View</a>
        {% endif %}
    </div>
</div>
{% endblock %}

datacommons/templates/schemas/view.html
{% extends "main.html" %}
{% block content %}

<div class="row">
    <div class="span8">
        <h2>{{ schema }}.{{ table }}</h2>
        <p><strong>Export:</strong> <a href="{% url "api-schemas-tables" schema table 'csv' %}?version_id={{ version.pk }}">CSV</a> | 
        <a href="{% url "api-schemas-tables" schema table 'json' %}?version_id={{ version.pk }}">JSON</a></p>

        {% include '_paginator.html' with paginator=rows %}

        <div class="overflowed">
            <table class="table table-striped">
                <thead>
                    <tr>
                    {% for col in cols %}
                        <th>{{ col.name }}</th>
                    {% endfor %}
                    </tr>
                    <tr>
                    {% for col in cols %}
                        <th class="field-type">{{ col.type_label }}</th>
                    {% endfor %}
                    </tr>
                </thead>
                {% for row in rows %}
                    <tr>
                        {% for col in row %}
                            <td>
                                {% if col.geom_type %}
                                    {{ col|truncatewords:1 }}
                                {% else %}
                                    {{ col }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>

        {% include '_paginator.html' with paginator=rows %}
    </div>

    <div class="span4">
        {% if versions %}
            <h4>Versions</h4>
            <ul>
                {% for v in versions %}
                    <li><a {% if version.pk == v.pk %}style="font-weight:bold"{% endif %}href="?version_id={{ v.pk }}">{{ v.created_on|date:"M-d-Y P" }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if show_restore_link %}
            <a href="{% url 'schemas-restore' version.pk %}" class="btn btn-small btn-warning">Restore to this version</a>
        {% endif %}
    </div>
</div>
{% endblock %}